import type { TournamentMatch } from '@/types';

export const SEVLIEVO_TOURNAMENT_ID = 'd5dc93b1-c302-4162-8c4b-5d799b77f93d';
export const SEVLIEVO_TOURNAMENT_NAME = 'Млади таланти - Севлиево  03-04.10.2026 г.';
export const SEVLIEVO_TOURNAMENT_URL = 'https://www.tournamentsoftware.com/tournament/d5dc93b1-c302-4162-8c4b-5d799b77f93d/Matches';

export const BULGARIAN_CLUBS_MAP: Record<string, string> = {
  "1": "БК Оряхово",
  "2": "БК Стара Загора",
  "3": "БК Хасково",
  "4": "БК Полски Тръмбеш",
  "5": "БК Академик Сф",
  "6": "БК Русе",
  "7": "БК Анета Янева - НСА",
  "8": "БК Брезово",
  "9": "БК Дружба Сф",
  "10": "БК Балкан Сф",
  "11": "БК Габрово",
  "12": "БК Ракетлон Варна",
  "13": "БК Виктори Сф",
  "14": "БК Севлиево",
  "15": "БК Боляри ВТ"
};

export const SEVLIEVO_REAL_MATCHES: TournamentMatch[] = [
  {
    "id": "TS-101",
    "matchNumber": "GS U13-Round1-01",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group A",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Рая Терзиева",
    "team1Club": "БК Хасково",
    "team2Player1": "Мария Младенова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-102",
    "matchNumber": "GS U13-Round1-02",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Сияна Николова",
    "team1Club": "БК Хасково",
    "team2Player1": "Борислава Иванова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-103",
    "matchNumber": "GS U13-Round1-03",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Габриела Петрова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Виктория Чиприянова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-104",
    "matchNumber": "GS U13-Round1-04",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Ева Георгиева",
    "team1Club": "БК Севлиево",
    "team2Player1": "Мишел Чипилова",
    "team2Club": "БК Виктори Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-105",
    "matchNumber": "GS U13-Round1-05",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Самуила Каменова",
    "team1Club": "БК Габрово",
    "team2Player1": "Елена Ангова",
    "team2Club": "БК Хасково",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-106",
    "matchNumber": "GS U13-Round1-06",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Теодора Йонкова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Никол Петкова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-107",
    "matchNumber": "GS U13-Round1-07",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Дара Павлова",
    "team1Club": "БК Виктори Сф",
    "team2Player1": "Тиана Атанасова",
    "team2Club": "БК Русе",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-108",
    "matchNumber": "GS U13-Round1-08",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group E",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Габриела Бошнакова",
    "team1Club": "БК Ракетлон Варна",
    "team2Player1": "Карина Венкова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-109",
    "matchNumber": "BS U13-Round1-09",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group A",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Киан Брейхи",
    "team1Club": "БК Дружба Сф",
    "team2Player1": "Симеон Петров",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-110",
    "matchNumber": "BS U13-Round1-10",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group B",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Виктор Боянов",
    "team1Club": "БК Ракетлон Варна",
    "team2Player1": "Артан Брейхи",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-111",
    "matchNumber": "BS U13-Round1-11",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group C",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Венцислав Драганов",
    "team1Club": "БК Дружба Сф",
    "team2Player1": "Станислав Пецев",
    "team2Club": "БК Стара Загора",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-112",
    "matchNumber": "BS U13-Round1-12",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group D",
    "round": "Round 1",
    "gameType": "singles",
    "team1Player1": "Константин Стоянов",
    "team1Club": "БК Ракетлон Варна",
    "team2Player1": "Николай Тодоров",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-113",
    "matchNumber": "GS U13-Round3-13",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group A",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Божидара Кожухарова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Мария Младенова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-114",
    "matchNumber": "GS U13-Round3-14",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Сияна Николова",
    "team1Club": "БК Хасково",
    "team2Player1": "Виктория Чиприянова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-115",
    "matchNumber": "GS U13-Round3-15",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Габриела Петрова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Борислава Иванова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-116",
    "matchNumber": "GS U13-Round3-16",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Ева Георгиева",
    "team1Club": "БК Севлиево",
    "team2Player1": "Елена Ангова",
    "team2Club": "БК Хасково",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-117",
    "matchNumber": "GS U13-Round3-17",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Самуила Каменова",
    "team1Club": "БК Габрово",
    "team2Player1": "Мишел Чипилова",
    "team2Club": "БК Виктори Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-118",
    "matchNumber": "GS U13-Round3-18",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Теодора Йонкова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Тиана Атанасова",
    "team2Club": "БК Русе",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-119",
    "matchNumber": "GS U13-Round3-19",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Дара Павлова",
    "team1Club": "БК Виктори Сф",
    "team2Player1": "Никол Петкова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-120",
    "matchNumber": "GS U13-Round3-20",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group E",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Татяна Георгиева",
    "team1Club": "БК Хасково",
    "team2Player1": "Карина Венкова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-121",
    "matchNumber": "BS U13-Round3-21",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group A",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Николай Петров",
    "team1Club": "БК Севлиево",
    "team2Player1": "Симеон Петров",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-122",
    "matchNumber": "BS U13-Round3-22",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group B",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Радостин Иванов",
    "team1Club": "БК Севлиево",
    "team2Player1": "Артан Брейхи",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-123",
    "matchNumber": "BS U13-Round3-23",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group C",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Максим Атанасов",
    "team1Club": "БК Ракетлон Варна",
    "team2Player1": "Станислав Пецев",
    "team2Club": "БК Стара Загора",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-124",
    "matchNumber": "BS U13-Round3-24",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group D",
    "round": "Round 3",
    "gameType": "singles",
    "team1Player1": "Григор Гатев",
    "team1Club": "БК Севлиево",
    "team2Player1": "Николай Тодоров",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-125",
    "matchNumber": "GS U13-Round2-25",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group A",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Божидара Кожухарова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Рая Терзиева",
    "team2Club": "БК Хасково",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-126",
    "matchNumber": "GS U13-Round2-26",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Сияна Николова",
    "team1Club": "БК Хасково",
    "team2Player1": "Габриела Петрова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-127",
    "matchNumber": "GS U13-Round2-27",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group B",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Виктория Чиприянова",
    "team1Club": "БК Габрово",
    "team2Player1": "Борислава Иванова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-128",
    "matchNumber": "GS U13-Round2-28",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Ева Георгиева",
    "team1Club": "БК Севлиево",
    "team2Player1": "Самуила Каменова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-129",
    "matchNumber": "GS U13-Round2-29",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group C",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Елена Ангова",
    "team1Club": "БК Хасково",
    "team2Player1": "Мишел Чипилова",
    "team2Club": "БК Виктори Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-130",
    "matchNumber": "GS U13-Round2-30",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Теодора Йонкова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Дара Павлова",
    "team2Club": "БК Виктори Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-131",
    "matchNumber": "GS U13-Round2-31",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group D",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Тиана Атанасова",
    "team1Club": "БК Русе",
    "team2Player1": "Никол Петкова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-132",
    "matchNumber": "GS U13-Round2-32",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13 - Group E",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Татяна Георгиева",
    "team1Club": "БК Хасково",
    "team2Player1": "Габриела Бошнакова",
    "team2Club": "БК Ракетлон Варна",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-133",
    "matchNumber": "BS U13-Round2-33",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group A",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Николай Петров",
    "team1Club": "БК Севлиево",
    "team2Player1": "Киан Брейхи",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-134",
    "matchNumber": "BS U13-Round2-34",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group B",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Радостин Иванов",
    "team1Club": "БК Севлиево",
    "team2Player1": "Виктор Боянов",
    "team2Club": "БК Ракетлон Варна",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-135",
    "matchNumber": "BS U13-Round2-35",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group C",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Максим Атанасов",
    "team1Club": "БК Ракетлон Варна",
    "team2Player1": "Венцислав Драганов",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-136",
    "matchNumber": "BS U13-Round2-36",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13 - Group D",
    "round": "Round 2",
    "gameType": "singles",
    "team1Player1": "Григор Гатев",
    "team1Club": "БК Севлиево",
    "team2Player1": "Константин Стоянов",
    "team2Club": "БК Ракетлон Варна",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-137",
    "matchNumber": "GS U13-Roundof16-37",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13",
    "round": "Round of 16",
    "gameType": "singles",
    "team1Player1": "Group E #1",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group B #2",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-138",
    "matchNumber": "GS U13-Roundof16-38",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13",
    "round": "Round of 16",
    "gameType": "singles",
    "team1Player1": "Group A #2",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group E #2",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-139",
    "matchNumber": "BS U13-Quarterfinal-39",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group A #1",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group C #2",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-140",
    "matchNumber": "BS U13-Quarterfinal-40",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group D #1",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group B #2",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-141",
    "matchNumber": "BS U13-Quarterfinal-41",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group A #2",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group C #1",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-142",
    "matchNumber": "BS U13-Quarterfinal-42",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "BS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group D #2",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group B #1",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-143",
    "matchNumber": "GS U13-Quarterfinal-43",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group A #1",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group C #2",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-144",
    "matchNumber": "GS U13-Quarterfinal-44",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GS U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Group D #2",
    "team1Club": "БК Севлиево",
    "team2Player1": "Group B #1",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-145",
    "matchNumber": "BD U13-Quarterfinal-45",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Артан Брейхи",
    "team1Club": "БК Дружба Сф",
    "team2Player1": "Киан Брейхи",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-146",
    "matchNumber": "BD U13-Quarterfinal-46",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Венцислав Драганов",
    "team1Club": "БК Дружба Сф",
    "team2Player1": "Григор Гатев",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-147",
    "matchNumber": "GD U13-Roundof16-47",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GD U13",
    "round": "Round of 16",
    "gameType": "singles",
    "team1Player1": "Виктория Чиприянова",
    "team1Club": "БК Габрово",
    "team2Player1": "Самуила Каменова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-148",
    "matchNumber": "GD U13-Quarterfinal-48",
    "courtNumber": "2",
    "scheduledTime": "09:30",
    "eventCategory": "GD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Божидара Кожухарова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Ева Георгиева",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-149",
    "matchNumber": "GD U13-Quarterfinal-49",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "GD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Мария Младенова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Никол Петкова",
    "team2Club": "БК Габрово",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-150",
    "matchNumber": "GD U13-Quarterfinal-50",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "GD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Борислава Иванова",
    "team1Club": "БК Севлиево",
    "team2Player1": "Габриела Петрова",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-151",
    "matchNumber": "GD U13-Quarterfinal-51",
    "courtNumber": "1",
    "scheduledTime": "09:30",
    "eventCategory": "GD U13",
    "round": "Quarter final",
    "gameType": "singles",
    "team1Player1": "Елена Ангова",
    "team1Club": "БК Хасково",
    "team2Player1": "Татяна Георгиева",
    "team2Club": "БК Хасково",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-152",
    "matchNumber": "BD U13-Semifinal-52",
    "courtNumber": "3",
    "scheduledTime": "09:30",
    "eventCategory": "BD U13",
    "round": "Semi final",
    "gameType": "singles",
    "team1Player1": "Николай Петров",
    "team1Club": "БК Севлиево",
    "team2Player1": "Радостин Иванов",
    "team2Club": "БК Севлиево",
    "format": "3x21",
    "status": "scheduled"
  },
  {
    "id": "TS-153",
    "matchNumber": "BD U13-Semifinal-53",
    "courtNumber": "4",
    "scheduledTime": "09:30",
    "eventCategory": "BD U13",
    "round": "Semi final",
    "gameType": "singles",
    "team1Player1": "Николай Тодоров",
    "team1Club": "БК Дружба Сф",
    "team2Player1": "Симеон Петров",
    "team2Club": "БК Дружба Сф",
    "format": "3x21",
    "status": "scheduled"
  }
];
